#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.ListManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="SageFrame")]
	public partial class ListManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ListManagementDataContext() :
        base(global::SageFrame.Core.Properties.Settings.Default.TempforSpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ListManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ListManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.sp_GetDefaultList")]
		public ISingleResult<sp_GetDefaultListResult> sp_GetDefaultList([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, culture);
			return ((ISingleResult<sp_GetDefaultListResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_GetListEntriesByNameParentKeyAndPortalID")]
		public ISingleResult<sp_GetListEntriesByNameParentKeyAndPortalIDResult> sp_GetListEntriesByNameParentKeyAndPortalID([Parameter(Name="ListName", DbType="NVarChar(50)")] string listName, [Parameter(Name="ParentKey", DbType="NVarChar(150)")] string parentKey, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, parentKey, portalID, culture);
			return ((ISingleResult<sp_GetListEntriesByNameParentKeyAndPortalIDResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_GetListsByPortalID")]
		public ISingleResult<sp_GetListsByPortalIDResult> sp_GetListsByPortalID([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, culture);
			return ((ISingleResult<sp_GetListsByPortalIDResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ListEntryUpdate")]
		public int sp_ListEntryUpdate([Parameter(Name="EntryID", DbType="Int")] System.Nullable<int> entryID, [Parameter(Name="Value", DbType="NVarChar(100)")] string value, [Parameter(Name="Text", DbType="NVarChar(150)")] string text, [Parameter(Name="CurrencyCode", DbType="NVarChar(50)")] string currencyCode, [Parameter(Name="DisplayLocale", DbType="NVarChar(50)")] string displayLocale, [Parameter(Name="Description", DbType="NVarChar(500)")] string description, [Parameter(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [Parameter(Name="UpdatedBy", DbType="NVarChar(256)")] string updatedBy, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryID, value, text, currencyCode, displayLocale, description, isActive, updatedBy, culture);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ListEntryAdd")]
		public ISingleResult<sp_ListEntryAddResult> sp_ListEntryAdd([Parameter(Name="ListName", DbType="NVarChar(50)")] string listName, [Parameter(Name="Value", DbType="NVarChar(100)")] string value, [Parameter(Name="Text", DbType="NVarChar(150)")] string text, [Parameter(Name="ParentID", DbType="Int")] System.Nullable<int> parentID, [Parameter(Name="Level", DbType="Int")] System.Nullable<int> level, [Parameter(Name="CurrencyCode", DbType="NVarChar(50)")] string currencyCode, [Parameter(Name="DisplayLocale", DbType="NVarChar(50)")] string displayLocale, [Parameter(Name="EnableDisplayOrder", DbType="Bit")] System.Nullable<bool> enableDisplayOrder, [Parameter(Name="DefinitionID", DbType="Int")] System.Nullable<int> definitionID, [Parameter(Name="Description", DbType="NVarChar(500)")] string description, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, [Parameter(Name="AddedBy", DbType="NVarChar(256)")] string addedBy, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, value, text, parentID, level, currencyCode, displayLocale, enableDisplayOrder, definitionID, description, portalID, isActive, addedBy, culture);
			return ((ISingleResult<sp_ListEntryAddResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_GetListEntrybyNameValueAndEntryID")]
		public ISingleResult<sp_GetListEntrybyNameValueAndEntryIDResult> sp_GetListEntrybyNameValueAndEntryID([Parameter(Name="ListName", DbType="NVarChar(50)")] string listName, [Parameter(Name="Value", DbType="NVarChar(200)")] string value, [Parameter(Name="EntryID", DbType="Int")] System.Nullable<int> entryID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, value, entryID, culture);
			return ((ISingleResult<sp_GetListEntrybyNameValueAndEntryIDResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_GetListEntrybyParentId")]
		public ISingleResult<sp_GetListEntrybyParentIdResult> sp_GetListEntrybyParentId([Parameter(Name="EntryID", DbType="Int")] System.Nullable<int> entryID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryID, culture);
			return ((ISingleResult<sp_GetListEntrybyParentIdResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ListEntryDeleteByID")]
		public int sp_ListEntryDeleteByID([Parameter(Name="EntryId", DbType="Int")] System.Nullable<int> entryId, [Parameter(Name="DeleteChild", DbType="Bit")] System.Nullable<bool> deleteChild, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryId, deleteChild, culture);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ListSortOrderUpdate")]
		public int sp_ListSortOrderUpdate([Parameter(Name="EntryID", DbType="Int")] System.Nullable<int> entryID, [Parameter(Name="MoveUp", DbType="Bit")] System.Nullable<bool> moveUp, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), entryID, moveUp, culture);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_GetListbyNameParentKeyAndPortalID")]
		public ISingleResult<sp_GetListbyNameParentKeyAndPortalIDResult> sp_GetListbyNameParentKeyAndPortalID([Parameter(Name="ListName", DbType="NVarChar(50)")] string listName, [Parameter(Name="ParentKey", DbType="NVarChar(150)")] string parentKey, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, parentKey, portalID, culture);
			return ((ISingleResult<sp_GetListbyNameParentKeyAndPortalIDResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ListDeleteByNameAndParentKey")]
		public int sp_ListDeleteByNameAndParentKey([Parameter(Name="ListName", DbType="NVarChar(50)")] string listName, [Parameter(Name="ParentKey", DbType="NVarChar(150)")] string parentKey, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, parentKey, culture);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_GetListEntrybyNameAndID")]
		public ISingleResult<sp_GetListEntrybyNameAndIDResult> sp_GetListEntrybyNameAndID([Parameter(Name="ListName", DbType="NVarChar(50)")] string listName, [Parameter(Name="EntryID", DbType="Int")] System.Nullable<int> entryID, [Parameter(Name="Culture", DbType="NVarChar(256)")] string culture)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), listName, entryID, culture);
			return ((ISingleResult<sp_GetListEntrybyNameAndIDResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_GetDefaultListResult
	{
		
		private string _ListName;
		
		private string _ParentKey;
		
		public sp_GetDefaultListResult()
		{
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
	}
	
	public partial class sp_GetListEntriesByNameParentKeyAndPortalIDResult
	{
		
		private int _EntryID;
		
		private string _ListName;
		
		private string _Value;
		
		private string _Text;
		
		private int _LEVEL;
		
		private string _CurrencyCode;
		
		private string _DisplayLocale;
		
		private int _DisplayOrder;
		
		private int _DefinitionID;
		
		private int _ParentID;
		
		private string _Description;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private string _Culture;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		private System.Nullable<int> _EntryCount;
		
		private System.Nullable<int> _HasChildren;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public sp_GetListEntriesByNameParentKeyAndPortalIDResult()
		{
		}
		
		[Column(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Storage="_Value", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[Column(Name="[LEVEL]", Storage="_LEVEL", DbType="Int NOT NULL")]
		public int LEVEL
		{
			get
			{
				return this._LEVEL;
			}
			set
			{
				if ((this._LEVEL != value))
				{
					this._LEVEL = value;
				}
			}
		}
		
		[Column(Storage="_CurrencyCode", DbType="NVarChar(50)")]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[Column(Storage="_DisplayLocale", DbType="NVarChar(50)")]
		public string DisplayLocale
		{
			get
			{
				return this._DisplayLocale;
			}
			set
			{
				if ((this._DisplayLocale != value))
				{
					this._DisplayLocale = value;
				}
			}
		}
		
		[Column(Storage="_DisplayOrder", DbType="Int NOT NULL")]
		public int DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[Column(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[Column(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[Column(Storage="_Culture", DbType="NVarChar(256)")]
		public string Culture
		{
			get
			{
				return this._Culture;
			}
			set
			{
				if ((this._Culture != value))
				{
					this._Culture = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[Column(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[Column(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[Column(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
		
		[Column(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[Column(Storage="_HasChildren", DbType="Int")]
		public System.Nullable<int> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this._HasChildren = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
	
	public partial class sp_GetListsByPortalIDResult
	{
		
		private string _ListName;
		
		private int _Level;
		
		private int _DefinitionID;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private System.Nullable<int> _EntryCount;
		
		private int _ParentID;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		public sp_GetListsByPortalIDResult()
		{
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[Column(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[Column(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[Column(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[Column(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[Column(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[Column(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
	}
	
	public partial class sp_ListEntryAddResult
	{
		
		private int _Column1;
		
		public sp_ListEntryAddResult()
		{
		}
		
		[Column(Storage="_Column1", DbType="Int NOT NULL")]
		public int Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class sp_GetListEntrybyNameValueAndEntryIDResult
	{
		
		private int _EntryID;
		
		private string _ListName;
		
		private string _Value;
		
		private string _Text;
		
		private int _LEVEL;
		
		private string _CurrencyCode;
		
		private string _DisplayLocale;
		
		private int _DisplayOrder;
		
		private int _DefinitionID;
		
		private int _ParentID;
		
		private string _Description;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private string _Culture;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		private System.Nullable<int> _EntryCount;
		
		private System.Nullable<int> _HasChildren;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public sp_GetListEntrybyNameValueAndEntryIDResult()
		{
		}
		
		[Column(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Storage="_Value", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[Column(Name="[LEVEL]", Storage="_LEVEL", DbType="Int NOT NULL")]
		public int LEVEL
		{
			get
			{
				return this._LEVEL;
			}
			set
			{
				if ((this._LEVEL != value))
				{
					this._LEVEL = value;
				}
			}
		}
		
		[Column(Storage="_CurrencyCode", DbType="NVarChar(50)")]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[Column(Storage="_DisplayLocale", DbType="NVarChar(50)")]
		public string DisplayLocale
		{
			get
			{
				return this._DisplayLocale;
			}
			set
			{
				if ((this._DisplayLocale != value))
				{
					this._DisplayLocale = value;
				}
			}
		}
		
		[Column(Storage="_DisplayOrder", DbType="Int NOT NULL")]
		public int DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[Column(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[Column(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[Column(Storage="_Culture", DbType="NVarChar(256)")]
		public string Culture
		{
			get
			{
				return this._Culture;
			}
			set
			{
				if ((this._Culture != value))
				{
					this._Culture = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[Column(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[Column(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[Column(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
		
		[Column(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[Column(Storage="_HasChildren", DbType="Int")]
		public System.Nullable<int> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this._HasChildren = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
	
	public partial class sp_GetListEntrybyParentIdResult
	{
		
		private int _EntryID;
		
		private string _ListName;
		
		private string _Value;
		
		private string _Text;
		
		private int _LEVEL;
		
		private string _CurrencyCode;
		
		private string _DisplayLocale;
		
		private int _DisplayOrder;
		
		private int _DefinitionID;
		
		private int _ParentID;
		
		private string _Description;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private string _Culture;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		private System.Nullable<int> _EntryCount;
		
		private System.Nullable<int> _HasChildren;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public sp_GetListEntrybyParentIdResult()
		{
		}
		
		[Column(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Storage="_Value", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[Column(Name="[LEVEL]", Storage="_LEVEL", DbType="Int NOT NULL")]
		public int LEVEL
		{
			get
			{
				return this._LEVEL;
			}
			set
			{
				if ((this._LEVEL != value))
				{
					this._LEVEL = value;
				}
			}
		}
		
		[Column(Storage="_CurrencyCode", DbType="NVarChar(50)")]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[Column(Storage="_DisplayLocale", DbType="NVarChar(50)")]
		public string DisplayLocale
		{
			get
			{
				return this._DisplayLocale;
			}
			set
			{
				if ((this._DisplayLocale != value))
				{
					this._DisplayLocale = value;
				}
			}
		}
		
		[Column(Storage="_DisplayOrder", DbType="Int NOT NULL")]
		public int DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[Column(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[Column(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[Column(Storage="_Culture", DbType="NVarChar(256)")]
		public string Culture
		{
			get
			{
				return this._Culture;
			}
			set
			{
				if ((this._Culture != value))
				{
					this._Culture = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[Column(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[Column(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[Column(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
		
		[Column(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[Column(Storage="_HasChildren", DbType="Int")]
		public System.Nullable<int> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this._HasChildren = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
	
	public partial class sp_GetListbyNameParentKeyAndPortalIDResult
	{
		
		private string _ListName;
		
		private int _Level;
		
		private int _DefinitionID;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private System.Nullable<int> _EntryCount;
		
		private int _ParentID;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		public sp_GetListbyNameParentKeyAndPortalIDResult()
		{
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Name="[Level]", Storage="_Level", DbType="Int NOT NULL")]
		public int Level
		{
			get
			{
				return this._Level;
			}
			set
			{
				if ((this._Level != value))
				{
					this._Level = value;
				}
			}
		}
		
		[Column(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[Column(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[Column(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[Column(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[Column(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[Column(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
	}
	
	public partial class sp_GetListEntrybyNameAndIDResult
	{
		
		private int _EntryID;
		
		private string _ListName;
		
		private string _Value;
		
		private string _Text;
		
		private int _LEVEL;
		
		private string _CurrencyCode;
		
		private string _DisplayLocale;
		
		private int _DisplayOrder;
		
		private int _DefinitionID;
		
		private int _ParentID;
		
		private string _Description;
		
		private int _PortalID;
		
		private bool _SystemList;
		
		private string _Culture;
		
		private string _ParentKey;
		
		private string _Parent;
		
		private string _ParentList;
		
		private System.Nullable<int> _MaxSortOrder;
		
		private System.Nullable<int> _EntryCount;
		
		private System.Nullable<int> _HasChildren;
		
		private System.Nullable<bool> _IsActive;
		
		private string _AddedBy;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _UpdatedBy;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		public sp_GetListEntrybyNameAndIDResult()
		{
		}
		
		[Column(Storage="_EntryID", DbType="Int NOT NULL")]
		public int EntryID
		{
			get
			{
				return this._EntryID;
			}
			set
			{
				if ((this._EntryID != value))
				{
					this._EntryID = value;
				}
			}
		}
		
		[Column(Storage="_ListName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ListName
		{
			get
			{
				return this._ListName;
			}
			set
			{
				if ((this._ListName != value))
				{
					this._ListName = value;
				}
			}
		}
		
		[Column(Storage="_Value", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[Column(Storage="_Text", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string Text
		{
			get
			{
				return this._Text;
			}
			set
			{
				if ((this._Text != value))
				{
					this._Text = value;
				}
			}
		}
		
		[Column(Name="[LEVEL]", Storage="_LEVEL", DbType="Int NOT NULL")]
		public int LEVEL
		{
			get
			{
				return this._LEVEL;
			}
			set
			{
				if ((this._LEVEL != value))
				{
					this._LEVEL = value;
				}
			}
		}
		
		[Column(Storage="_CurrencyCode", DbType="NVarChar(50)")]
		public string CurrencyCode
		{
			get
			{
				return this._CurrencyCode;
			}
			set
			{
				if ((this._CurrencyCode != value))
				{
					this._CurrencyCode = value;
				}
			}
		}
		
		[Column(Storage="_DisplayLocale", DbType="NVarChar(50)")]
		public string DisplayLocale
		{
			get
			{
				return this._DisplayLocale;
			}
			set
			{
				if ((this._DisplayLocale != value))
				{
					this._DisplayLocale = value;
				}
			}
		}
		
		[Column(Storage="_DisplayOrder", DbType="Int NOT NULL")]
		public int DisplayOrder
		{
			get
			{
				return this._DisplayOrder;
			}
			set
			{
				if ((this._DisplayOrder != value))
				{
					this._DisplayOrder = value;
				}
			}
		}
		
		[Column(Storage="_DefinitionID", DbType="Int NOT NULL")]
		public int DefinitionID
		{
			get
			{
				return this._DefinitionID;
			}
			set
			{
				if ((this._DefinitionID != value))
				{
					this._DefinitionID = value;
				}
			}
		}
		
		[Column(Storage="_ParentID", DbType="Int NOT NULL")]
		public int ParentID
		{
			get
			{
				return this._ParentID;
			}
			set
			{
				if ((this._ParentID != value))
				{
					this._ParentID = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int NOT NULL")]
		public int PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_SystemList", DbType="Bit NOT NULL")]
		public bool SystemList
		{
			get
			{
				return this._SystemList;
			}
			set
			{
				if ((this._SystemList != value))
				{
					this._SystemList = value;
				}
			}
		}
		
		[Column(Storage="_Culture", DbType="NVarChar(256)")]
		public string Culture
		{
			get
			{
				return this._Culture;
			}
			set
			{
				if ((this._Culture != value))
				{
					this._Culture = value;
				}
			}
		}
		
		[Column(Storage="_ParentKey", DbType="NVarChar(2000)")]
		public string ParentKey
		{
			get
			{
				return this._ParentKey;
			}
			set
			{
				if ((this._ParentKey != value))
				{
					this._ParentKey = value;
				}
			}
		}
		
		[Column(Storage="_Parent", DbType="NVarChar(2000)")]
		public string Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this._Parent = value;
				}
			}
		}
		
		[Column(Storage="_ParentList", DbType="NVarChar(2000)")]
		public string ParentList
		{
			get
			{
				return this._ParentList;
			}
			set
			{
				if ((this._ParentList != value))
				{
					this._ParentList = value;
				}
			}
		}
		
		[Column(Storage="_MaxSortOrder", DbType="Int")]
		public System.Nullable<int> MaxSortOrder
		{
			get
			{
				return this._MaxSortOrder;
			}
			set
			{
				if ((this._MaxSortOrder != value))
				{
					this._MaxSortOrder = value;
				}
			}
		}
		
		[Column(Storage="_EntryCount", DbType="Int")]
		public System.Nullable<int> EntryCount
		{
			get
			{
				return this._EntryCount;
			}
			set
			{
				if ((this._EntryCount != value))
				{
					this._EntryCount = value;
				}
			}
		}
		
		[Column(Storage="_HasChildren", DbType="Int")]
		public System.Nullable<int> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this._HasChildren = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
