#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.Template
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="SageFrameWebSite")]
	public partial class TemplateDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public TemplateDataContext() : 
				base(global::SageFrame.Core.Properties.Settings.Default.SageFrameConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TemplateDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TemplateDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TemplateDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TemplateDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.sp_TemplateAdd")]
		public int sp_TemplateAdd([Parameter(Name="TemplateTitle", DbType="NVarChar(256)")] string templateTitle, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), templateTitle, portalID, username);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_TemplateDelete")]
		public ISingleResult<sp_TemplateDeleteResult> sp_TemplateDelete([Parameter(Name="TemplateID", DbType="Int")] System.Nullable<int> templateID, [Parameter(Name="TemplateTitle", DbType="NVarChar(256)")] string templateTitle, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), templateID, templateTitle, portalID, username);
			return ((ISingleResult<sp_TemplateDeleteResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_TemplateGetList")]
		public ISingleResult<sp_TemplateGetListResult> sp_TemplateGetList([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, username);
			return ((ISingleResult<sp_TemplateGetListResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_TemplateDeleteResult
	{
		
		private int _ReturnCode;
		
		private string _ReturnMessage;
		
		public sp_TemplateDeleteResult()
		{
		}
		
		[Column(Storage="_ReturnCode", DbType="Int NOT NULL")]
		public int ReturnCode
		{
			get
			{
				return this._ReturnCode;
			}
			set
			{
				if ((this._ReturnCode != value))
				{
					this._ReturnCode = value;
				}
			}
		}
		
		[Column(Storage="_ReturnMessage", DbType="VarChar(51) NOT NULL", CanBeNull=false)]
		public string ReturnMessage
		{
			get
			{
				return this._ReturnMessage;
			}
			set
			{
				if ((this._ReturnMessage != value))
				{
					this._ReturnMessage = value;
				}
			}
		}
	}
	
	public partial class sp_TemplateGetListResult
	{
		
		private int _TemplateID;
		
		private string _TemplateTitle;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private string _AddedBy;
		
		public sp_TemplateGetListResult()
		{
		}
		
		[Column(Storage="_TemplateID", DbType="Int NOT NULL")]
		public int TemplateID
		{
			get
			{
				return this._TemplateID;
			}
			set
			{
				if ((this._TemplateID != value))
				{
					this._TemplateID = value;
				}
			}
		}
		
		[Column(Storage="_TemplateTitle", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string TemplateTitle
		{
			get
			{
				return this._TemplateTitle;
			}
			set
			{
				if ((this._TemplateTitle != value))
				{
					this._TemplateTitle = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
