#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.Packages
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="SageFrame")]
	public partial class PackagesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PackagesDataContext() :
        base(global::SageFrame.Core.Properties.Settings.Default.TempforSpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PackagesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackagesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackagesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PackagesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.sp_PackagesAdd")]
		public int sp_PackagesAdd(
					[Parameter(Name="PackageID", DbType="Int")] ref System.Nullable<int> packageID, 
					[Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, 
					[Parameter(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID, 
					[Parameter(Name="Name", DbType="NVarChar(128)")] string name, 
					[Parameter(Name="FriendlyName", DbType="NVarChar(250)")] string friendlyName, 
					[Parameter(Name="Description", DbType="NVarChar(2000)")] string description, 
					[Parameter(Name="PackageType", DbType="NVarChar(100)")] string packageType, 
					[Parameter(Name="Version", DbType="NVarChar(50)")] string version, 
					[Parameter(Name="License", DbType="NText")] string license, 
					[Parameter(Name="Manifest", DbType="NText")] string manifest, 
					[Parameter(Name="Owner", DbType="NVarChar(100)")] string owner, 
					[Parameter(Name="Organization", DbType="NVarChar(100)")] string organization, 
					[Parameter(Name="Url", DbType="NVarChar(250)")] string url, 
					[Parameter(Name="Email", DbType="NVarChar(100)")] string email, 
					[Parameter(Name="ReleaseNotes", DbType="NText")] string releaseNotes, 
					[Parameter(Name="IsSystemPackage", DbType="Bit")] System.Nullable<bool> isSystemPackage, 
					[Parameter(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[Parameter(Name="AddedOn", DbType="DateTime")] System.Nullable<System.DateTime> addedOn, 
					[Parameter(Name="AddedBy", DbType="NVarChar(256)")] string addedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), packageID, portalID, moduleID, name, friendlyName, description, packageType, version, license, manifest, owner, organization, url, email, releaseNotes, isSystemPackage, isActive, addedOn, addedBy);
			packageID = ((System.Nullable<int>)(result.GetParameterValue(0)));
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesDelete")]
		public int sp_PackagesDelete([Parameter(Name="PackageID", DbType="Int")] System.Nullable<int> packageID, [Parameter(Name="DeletedBy", DbType="NVarChar(256)")] string deletedBy, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), packageID, deletedBy, portalID);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesGetByModuleIDAndPortalID")]
		public ISingleResult<sp_PackagesGetByModuleIDAndPortalIDResult> sp_PackagesGetByModuleIDAndPortalID([Parameter(Name="PackageID", DbType="Int")] System.Nullable<int> packageID, [Parameter(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), packageID, moduleID, portalID);
			return ((ISingleResult<sp_PackagesGetByModuleIDAndPortalIDResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesGetByModules")]
		public ISingleResult<sp_PackagesGetByModulesResult> sp_PackagesGetByModules([Parameter(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleID);
			return ((ISingleResult<sp_PackagesGetByModulesResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesList")]
		public ISingleResult<sp_PackagesListResult> sp_PackagesList()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<sp_PackagesListResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesUpdate")]
		public int sp_PackagesUpdate(
					[Parameter(Name="PackageID", DbType="Int")] System.Nullable<int> packageID, 
					[Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, 
					[Parameter(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID, 
					[Parameter(Name="Name", DbType="NVarChar(128)")] string name, 
					[Parameter(Name="FriendlyName", DbType="NVarChar(250)")] string friendlyName, 
					[Parameter(Name="Description", DbType="NVarChar(2000)")] string description, 
					[Parameter(Name="PackageType", DbType="NVarChar(100)")] string packageType, 
					[Parameter(Name="Version", DbType="NVarChar(50)")] string version, 
					[Parameter(Name="License", DbType="NText")] string license, 
					[Parameter(Name="Manifest", DbType="NText")] string manifest, 
					[Parameter(Name="Owner", DbType="NVarChar(100)")] string owner, 
					[Parameter(Name="Organization", DbType="NVarChar(100)")] string organization, 
					[Parameter(Name="Url", DbType="NVarChar(250)")] string url, 
					[Parameter(Name="Email", DbType="NVarChar(100)")] string email, 
					[Parameter(Name="ReleaseNotes", DbType="NText")] string releaseNotes, 
					[Parameter(Name="IsSystemPackage", DbType="Bit")] System.Nullable<bool> isSystemPackage, 
					[Parameter(Name="IsActive", DbType="Bit")] System.Nullable<bool> isActive, 
					[Parameter(Name="IsModified", DbType="Bit")] System.Nullable<bool> isModified, 
					[Parameter(Name="UpdatedOn", DbType="DateTime")] System.Nullable<System.DateTime> updatedOn, 
					[Parameter(Name="UpdatedBy", DbType="NVarChar(256)")] string updatedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), packageID, portalID, moduleID, name, friendlyName, description, packageType, version, license, manifest, owner, organization, url, email, releaseNotes, isSystemPackage, isActive, isModified, updatedOn, updatedBy);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_ExtensionUpdate")]
		public int sp_ExtensionUpdate(
					[Parameter(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID, 
					[Parameter(Name="FolderName", DbType="NVarChar(128)")] string folderName, 
					[Parameter(Name="BusinessControllerClass", DbType="NVarChar(200)")] string businessControllerClass, 
					[Parameter(Name="Dependencies", DbType="NVarChar(400)")] string dependencies, 
					[Parameter(Name="Permissions", DbType="NVarChar(400)")] string permissions, 
					[Parameter(Name="IsPortable", DbType="Bit")] System.Nullable<bool> isPortable, 
					[Parameter(Name="IsSearchable", DbType="Bit")] System.Nullable<bool> isSearchable, 
					[Parameter(Name="IsUpgradable", DbType="Bit")] System.Nullable<bool> isUpgradable, 
					[Parameter(Name="IsPremium", DbType="Bit")] System.Nullable<bool> isPremium, 
					[Parameter(Name="PackageName", DbType="NVarChar(128)")] string packageName, 
					[Parameter(Name="PackageDescription", DbType="NVarChar(2000)")] string packageDescription, 
					[Parameter(Name="Version", DbType="NVarChar(50)")] string version, 
					[Parameter(Name="License", DbType="NText")] string license, 
					[Parameter(Name="ReleaseNotes", DbType="NText")] string releaseNotes, 
					[Parameter(Name="Owner", DbType="NVarChar(100)")] string owner, 
					[Parameter(Name="Organization", DbType="NVarChar(100)")] string organization, 
					[Parameter(Name="Url", DbType="NVarChar(250)")] string url, 
					[Parameter(Name="Email", DbType="NVarChar(100)")] string email, 
					[Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, 
					[Parameter(Name="Username", DbType="NVarChar(256)")] string username)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleID, folderName, businessControllerClass, dependencies, permissions, isPortable, isSearchable, isUpgradable, isPremium, packageName, packageDescription, version, license, releaseNotes, owner, organization, url, email, portalID, username);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesDeleteByModuleID")]
		public int sp_PackagesDeleteByModuleID([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="ModuleID", DbType="Int")] System.Nullable<int> moduleID, [Parameter(Name="DeletedBy", DbType="NVarChar(256)")] string deletedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, moduleID, deletedBy);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesUpdateChanges")]
		public int sp_PackagesUpdateChanges([Parameter(Name="ModuleIDs", DbType="NVarChar(4000)")] string moduleIDs, [Parameter(Name="IsActives", DbType="NVarChar(4000)")] string isActives, [Parameter(Name="UpdatedBy", DbType="NVarChar(256)")] string updatedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), moduleIDs, isActives, updatedBy);
			return ((int)(result.ReturnValue));
		}
		
		[Function(Name="dbo.sp_PackagesGetByPortalID")]
		public ISingleResult<sp_PackagesGetByPortalIDResult> sp_PackagesGetByPortalID([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="SearchText", DbType="NVarChar(4000)")] string searchText)
		{
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, searchText);
			return ((ISingleResult<sp_PackagesGetByPortalIDResult>)(result.ReturnValue));
		}
	}
	
	public partial class sp_PackagesGetByModuleIDAndPortalIDResult
	{
		
		private int _PackageID;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<int> _ModuleID;
		
		private string _Name;
		
		private string _FriendlyName;
		
		private string _Description;
		
		private string _PackageType;
		
		private string _Version;
		
		private string _License;
		
		private string _Manifest;
		
		private string _Owner;
		
		private string _Organization;
		
		private string _Url;
		
		private string _Email;
		
		private string _ReleaseNotes;
		
		private bool _IsSystemPackage;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_PackagesGetByModuleIDAndPortalIDResult()
		{
		}
		
		[Column(Storage="_PackageID", DbType="Int NOT NULL")]
		public int PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this._PackageID = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_ModuleID", DbType="Int")]
		public System.Nullable<int> ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this._ModuleID = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_FriendlyName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FriendlyName
		{
			get
			{
				return this._FriendlyName;
			}
			set
			{
				if ((this._FriendlyName != value))
				{
					this._FriendlyName = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PackageType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PackageType
		{
			get
			{
				return this._PackageType;
			}
			set
			{
				if ((this._PackageType != value))
				{
					this._PackageType = value;
				}
			}
		}
		
		[Column(Storage="_Version", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[Column(Storage="_License", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this._License = value;
				}
			}
		}
		
		[Column(Storage="_Manifest", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Manifest
		{
			get
			{
				return this._Manifest;
			}
			set
			{
				if ((this._Manifest != value))
				{
					this._Manifest = value;
				}
			}
		}
		
		[Column(Storage="_Owner", DbType="NVarChar(100)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this._Owner = value;
				}
			}
		}
		
		[Column(Storage="_Organization", DbType="NVarChar(100)")]
		public string Organization
		{
			get
			{
				return this._Organization;
			}
			set
			{
				if ((this._Organization != value))
				{
					this._Organization = value;
				}
			}
		}
		
		[Column(Storage="_Url", DbType="NVarChar(250)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_ReleaseNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ReleaseNotes
		{
			get
			{
				return this._ReleaseNotes;
			}
			set
			{
				if ((this._ReleaseNotes != value))
				{
					this._ReleaseNotes = value;
				}
			}
		}
		
		[Column(Storage="_IsSystemPackage", DbType="Bit NOT NULL")]
		public bool IsSystemPackage
		{
			get
			{
				return this._IsSystemPackage;
			}
			set
			{
				if ((this._IsSystemPackage != value))
				{
					this._IsSystemPackage = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[Column(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[Column(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
	
	public partial class sp_PackagesGetByModulesResult
	{
		
		private int _PackageID;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<int> _ModuleID;
		
		private string _Name;
		
		private string _FriendlyName;
		
		private string _Description;
		
		private string _PackageType;
		
		private string _Version;
		
		private string _License;
		
		private string _Manifest;
		
		private string _Owner;
		
		private string _Organization;
		
		private string _Url;
		
		private string _Email;
		
		private string _ReleaseNotes;
		
		private bool _IsSystemPackage;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_PackagesGetByModulesResult()
		{
		}
		
		[Column(Storage="_PackageID", DbType="Int NOT NULL")]
		public int PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this._PackageID = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_ModuleID", DbType="Int")]
		public System.Nullable<int> ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this._ModuleID = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_FriendlyName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FriendlyName
		{
			get
			{
				return this._FriendlyName;
			}
			set
			{
				if ((this._FriendlyName != value))
				{
					this._FriendlyName = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PackageType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PackageType
		{
			get
			{
				return this._PackageType;
			}
			set
			{
				if ((this._PackageType != value))
				{
					this._PackageType = value;
				}
			}
		}
		
		[Column(Storage="_Version", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[Column(Storage="_License", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this._License = value;
				}
			}
		}
		
		[Column(Storage="_Manifest", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Manifest
		{
			get
			{
				return this._Manifest;
			}
			set
			{
				if ((this._Manifest != value))
				{
					this._Manifest = value;
				}
			}
		}
		
		[Column(Storage="_Owner", DbType="NVarChar(100)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this._Owner = value;
				}
			}
		}
		
		[Column(Storage="_Organization", DbType="NVarChar(100)")]
		public string Organization
		{
			get
			{
				return this._Organization;
			}
			set
			{
				if ((this._Organization != value))
				{
					this._Organization = value;
				}
			}
		}
		
		[Column(Storage="_Url", DbType="NVarChar(250)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_ReleaseNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ReleaseNotes
		{
			get
			{
				return this._ReleaseNotes;
			}
			set
			{
				if ((this._ReleaseNotes != value))
				{
					this._ReleaseNotes = value;
				}
			}
		}
		
		[Column(Storage="_IsSystemPackage", DbType="Bit NOT NULL")]
		public bool IsSystemPackage
		{
			get
			{
				return this._IsSystemPackage;
			}
			set
			{
				if ((this._IsSystemPackage != value))
				{
					this._IsSystemPackage = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[Column(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[Column(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
	
	public partial class sp_PackagesListResult
	{
		
		private int _PackageID;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<int> _ModuleID;
		
		private string _Name;
		
		private string _FriendlyName;
		
		private string _Description;
		
		private string _PackageType;
		
		private string _Version;
		
		private string _License;
		
		private string _Manifest;
		
		private string _Owner;
		
		private string _Organization;
		
		private string _Url;
		
		private string _Email;
		
		private string _ReleaseNotes;
		
		private bool _IsSystemPackage;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		public sp_PackagesListResult()
		{
		}
		
		[Column(Storage="_PackageID", DbType="Int NOT NULL")]
		public int PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this._PackageID = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_ModuleID", DbType="Int")]
		public System.Nullable<int> ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this._ModuleID = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_FriendlyName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FriendlyName
		{
			get
			{
				return this._FriendlyName;
			}
			set
			{
				if ((this._FriendlyName != value))
				{
					this._FriendlyName = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PackageType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PackageType
		{
			get
			{
				return this._PackageType;
			}
			set
			{
				if ((this._PackageType != value))
				{
					this._PackageType = value;
				}
			}
		}
		
		[Column(Storage="_Version", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[Column(Storage="_License", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this._License = value;
				}
			}
		}
		
		[Column(Storage="_Manifest", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Manifest
		{
			get
			{
				return this._Manifest;
			}
			set
			{
				if ((this._Manifest != value))
				{
					this._Manifest = value;
				}
			}
		}
		
		[Column(Storage="_Owner", DbType="NVarChar(100)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this._Owner = value;
				}
			}
		}
		
		[Column(Storage="_Organization", DbType="NVarChar(100)")]
		public string Organization
		{
			get
			{
				return this._Organization;
			}
			set
			{
				if ((this._Organization != value))
				{
					this._Organization = value;
				}
			}
		}
		
		[Column(Storage="_Url", DbType="NVarChar(250)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_ReleaseNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ReleaseNotes
		{
			get
			{
				return this._ReleaseNotes;
			}
			set
			{
				if ((this._ReleaseNotes != value))
				{
					this._ReleaseNotes = value;
				}
			}
		}
		
		[Column(Storage="_IsSystemPackage", DbType="Bit NOT NULL")]
		public bool IsSystemPackage
		{
			get
			{
				return this._IsSystemPackage;
			}
			set
			{
				if ((this._IsSystemPackage != value))
				{
					this._IsSystemPackage = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[Column(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[Column(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
	}
	
	public partial class sp_PackagesGetByPortalIDResult
	{
		
		private int _PackageID;
		
		private System.Nullable<int> _PortalID;
		
		private System.Nullable<int> _ModuleID;
		
		private string _Name;
		
		private string _FriendlyName;
		
		private string _Description;
		
		private string _PackageType;
		
		private string _Version;
		
		private string _License;
		
		private string _Manifest;
		
		private string _Owner;
		
		private string _Organization;
		
		private string _Url;
		
		private string _Email;
		
		private string _ReleaseNotes;
		
		private bool _IsSystemPackage;
		
		private System.Nullable<bool> _IsActive;
		
		private System.Nullable<bool> _IsDeleted;
		
		private System.Nullable<bool> _IsModified;
		
		private System.Nullable<System.DateTime> _AddedOn;
		
		private System.Nullable<System.DateTime> _UpdatedOn;
		
		private System.Nullable<System.DateTime> _DeletedOn;
		
		private string _AddedBy;
		
		private string _UpdatedBy;
		
		private string _DeletedBy;
		
		private System.Nullable<int> _InUse;
		
		private System.Nullable<bool> _IsAdmin;
		
		public sp_PackagesGetByPortalIDResult()
		{
		}
		
		[Column(Storage="_PackageID", DbType="Int NOT NULL")]
		public int PackageID
		{
			get
			{
				return this._PackageID;
			}
			set
			{
				if ((this._PackageID != value))
				{
					this._PackageID = value;
				}
			}
		}
		
		[Column(Storage="_PortalID", DbType="Int")]
		public System.Nullable<int> PortalID
		{
			get
			{
				return this._PortalID;
			}
			set
			{
				if ((this._PortalID != value))
				{
					this._PortalID = value;
				}
			}
		}
		
		[Column(Storage="_ModuleID", DbType="Int")]
		public System.Nullable<int> ModuleID
		{
			get
			{
				return this._ModuleID;
			}
			set
			{
				if ((this._ModuleID != value))
				{
					this._ModuleID = value;
				}
			}
		}
		
		[Column(Storage="_Name", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[Column(Storage="_FriendlyName", DbType="NVarChar(250) NOT NULL", CanBeNull=false)]
		public string FriendlyName
		{
			get
			{
				return this._FriendlyName;
			}
			set
			{
				if ((this._FriendlyName != value))
				{
					this._FriendlyName = value;
				}
			}
		}
		
		[Column(Storage="_Description", DbType="NVarChar(2000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[Column(Storage="_PackageType", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PackageType
		{
			get
			{
				return this._PackageType;
			}
			set
			{
				if ((this._PackageType != value))
				{
					this._PackageType = value;
				}
			}
		}
		
		[Column(Storage="_Version", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Version
		{
			get
			{
				return this._Version;
			}
			set
			{
				if ((this._Version != value))
				{
					this._Version = value;
				}
			}
		}
		
		[Column(Storage="_License", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string License
		{
			get
			{
				return this._License;
			}
			set
			{
				if ((this._License != value))
				{
					this._License = value;
				}
			}
		}
		
		[Column(Storage="_Manifest", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string Manifest
		{
			get
			{
				return this._Manifest;
			}
			set
			{
				if ((this._Manifest != value))
				{
					this._Manifest = value;
				}
			}
		}
		
		[Column(Storage="_Owner", DbType="NVarChar(100)")]
		public string Owner
		{
			get
			{
				return this._Owner;
			}
			set
			{
				if ((this._Owner != value))
				{
					this._Owner = value;
				}
			}
		}
		
		[Column(Storage="_Organization", DbType="NVarChar(100)")]
		public string Organization
		{
			get
			{
				return this._Organization;
			}
			set
			{
				if ((this._Organization != value))
				{
					this._Organization = value;
				}
			}
		}
		
		[Column(Storage="_Url", DbType="NVarChar(250)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
		
		[Column(Storage="_Email", DbType="NVarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[Column(Storage="_ReleaseNotes", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string ReleaseNotes
		{
			get
			{
				return this._ReleaseNotes;
			}
			set
			{
				if ((this._ReleaseNotes != value))
				{
					this._ReleaseNotes = value;
				}
			}
		}
		
		[Column(Storage="_IsSystemPackage", DbType="Bit NOT NULL")]
		public bool IsSystemPackage
		{
			get
			{
				return this._IsSystemPackage;
			}
			set
			{
				if ((this._IsSystemPackage != value))
				{
					this._IsSystemPackage = value;
				}
			}
		}
		
		[Column(Storage="_IsActive", DbType="Bit")]
		public System.Nullable<bool> IsActive
		{
			get
			{
				return this._IsActive;
			}
			set
			{
				if ((this._IsActive != value))
				{
					this._IsActive = value;
				}
			}
		}
		
		[Column(Storage="_IsDeleted", DbType="Bit")]
		public System.Nullable<bool> IsDeleted
		{
			get
			{
				return this._IsDeleted;
			}
			set
			{
				if ((this._IsDeleted != value))
				{
					this._IsDeleted = value;
				}
			}
		}
		
		[Column(Storage="_IsModified", DbType="Bit")]
		public System.Nullable<bool> IsModified
		{
			get
			{
				return this._IsModified;
			}
			set
			{
				if ((this._IsModified != value))
				{
					this._IsModified = value;
				}
			}
		}
		
		[Column(Storage="_AddedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> AddedOn
		{
			get
			{
				return this._AddedOn;
			}
			set
			{
				if ((this._AddedOn != value))
				{
					this._AddedOn = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> UpdatedOn
		{
			get
			{
				return this._UpdatedOn;
			}
			set
			{
				if ((this._UpdatedOn != value))
				{
					this._UpdatedOn = value;
				}
			}
		}
		
		[Column(Storage="_DeletedOn", DbType="DateTime")]
		public System.Nullable<System.DateTime> DeletedOn
		{
			get
			{
				return this._DeletedOn;
			}
			set
			{
				if ((this._DeletedOn != value))
				{
					this._DeletedOn = value;
				}
			}
		}
		
		[Column(Storage="_AddedBy", DbType="NVarChar(256)")]
		public string AddedBy
		{
			get
			{
				return this._AddedBy;
			}
			set
			{
				if ((this._AddedBy != value))
				{
					this._AddedBy = value;
				}
			}
		}
		
		[Column(Storage="_UpdatedBy", DbType="NVarChar(256)")]
		public string UpdatedBy
		{
			get
			{
				return this._UpdatedBy;
			}
			set
			{
				if ((this._UpdatedBy != value))
				{
					this._UpdatedBy = value;
				}
			}
		}
		
		[Column(Storage="_DeletedBy", DbType="NVarChar(256)")]
		public string DeletedBy
		{
			get
			{
				return this._DeletedBy;
			}
			set
			{
				if ((this._DeletedBy != value))
				{
					this._DeletedBy = value;
				}
			}
		}
		
		[Column(Storage="_InUse", DbType="Int")]
		public System.Nullable<int> InUse
		{
			get
			{
				return this._InUse;
			}
			set
			{
				if ((this._InUse != value))
				{
					this._InUse = value;
				}
			}
		}
		
		[Column(Storage="_IsAdmin", DbType="Bit")]
		public System.Nullable<bool> IsAdmin
		{
			get
			{
				return this._IsAdmin;
			}
			set
			{
				if ((this._IsAdmin != value))
				{
					this._IsAdmin = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
