#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.SessionLog
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="SageFrame")]
	public partial class SessionLogDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public SessionLogDataContext() :
        base(global::SageFrame.Core.Properties.Settings.Default.TempforSpConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SessionLogDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionLogDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionLogDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SessionLogDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[Function(Name="dbo.sp_SessionTrackerAdd")]
		public int sp_SessionTrackerAdd([Parameter(Name="SessionUserHostAddress", DbType="NVarChar(500)")] string sessionUserHostAddress, [Parameter(Name="SessionUserAgent", DbType="NVarChar(500)")] string sessionUserAgent, [Parameter(Name="SessionBrowser", DbType="NVarChar(500)")] string sessionBrowser, [Parameter(Name="SessionCrawler", DbType="NVarChar(500)")] string sessionCrawler, [Parameter(Name="SessionURL", DbType="NVarChar(500)")] string sessionURL, [Parameter(Name="SessionVisitCount", DbType="Int")] System.Nullable<int> sessionVisitCount, [Parameter(Name="SessionOriginalReferrer", DbType="NVarChar(500)")] string sessionOriginalReferrer, [Parameter(Name="SessionOriginalURL", DbType="NVarChar(500)")] string sessionOriginalURL, [Parameter(Name="Username", DbType="NVarChar(256)")] string username, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sessionUserHostAddress, sessionUserAgent, sessionBrowser, sessionCrawler, sessionURL, sessionVisitCount, sessionOriginalReferrer, sessionOriginalURL, username, portalID);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
