using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Reflection;

#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SageFrame.PortalSetting
{
    [System.Data.Linq.Mapping.Database(Name="AspxCommerceNOV19")]
    public partial class PortalSettingDataContext : System.Data.Linq.DataContext
    {
		
        private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
        #region Extensibility Method Definitions
        partial void OnCreated();
        #endregion
		
        public PortalSettingDataContext() : 
            base(global::SageFrame.Core.Properties.Settings.Default.AspxCommerceNOV19ConnectionString, mappingSource)
        {
            OnCreated();
        }
		
        public PortalSettingDataContext(string connection) : 
            base(connection, mappingSource)
        {
            OnCreated();
        }
		
        public PortalSettingDataContext(System.Data.IDbConnection connection) : 
            base(connection, mappingSource)
        {
            OnCreated();
        }
		
        public PortalSettingDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
            base(connection, mappingSource)
        {
            OnCreated();
        }
		
        public PortalSettingDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
            base(connection, mappingSource)
        {
            OnCreated();
        }
		
        [Function(Name="dbo.sp_SettingAdd")]
        public int sp_SettingAdd([Parameter(Name="SettingID", DbType="Int")] ref System.Nullable<int> settingID, [Parameter(Name="Name", DbType="NVarChar(200)")] string name, [Parameter(Name="Value", DbType="NVarChar(2000)")] string value, [Parameter(Name="Description", DbType="NText")] string description)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID, name, value, description);
            settingID = ((System.Nullable<int>)(result.GetParameterValue(0)));
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingBySettingID")]
        public ISingleResult<sp_SettingBySettingIDResult> sp_SettingBySettingID([Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID);
            return ((ISingleResult<sp_SettingBySettingIDResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingDelete")]
        public int sp_SettingDelete([Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID, portalID);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingList")]
        public ISingleResult<sp_SettingListResult> sp_SettingList()
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
            return ((ISingleResult<sp_SettingListResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalAddUpdateList")]
        public int sp_SettingPortalAddUpdateList([Parameter(DbType="NVarChar(4000)")] string strKeyes, [Parameter(DbType="NVarChar(4000)")] string strValues, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Return", DbType="Int")] ref System.Nullable<int> @return)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), strKeyes, strValues, portalID, @return);
            @return = ((System.Nullable<int>)(result.GetParameterValue(3)));
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalAdd")]
        public int sp_SettingPortalAdd([Parameter(Name="SettingPortal", DbType="Int")] ref System.Nullable<int> settingPortal, [Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID, [Parameter(Name="Value", DbType="NVarChar(2000)")] string value, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingPortal, settingID, value, portalID);
            settingPortal = ((System.Nullable<int>)(result.GetParameterValue(0)));
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalByPortalID")]
        public ISingleResult<sp_SettingPortalByPortalIDResult> sp_SettingPortalByPortalID([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID);
            return ((ISingleResult<sp_SettingPortalByPortalIDResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalBySettingID")]
        public ISingleResult<sp_SettingPortalBySettingIDResult> sp_SettingPortalBySettingID([Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID, portalID);
            return ((ISingleResult<sp_SettingPortalBySettingIDResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalDelete")]
        public int sp_SettingPortalDelete([Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID, portalID);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalList")]
        public ISingleResult<sp_SettingPortalListResult> sp_SettingPortalList()
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
            return ((ISingleResult<sp_SettingPortalListResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingPortalUpdate")]
        public int sp_SettingPortalUpdate([Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID, [Parameter(Name="Value", DbType="NVarChar(2000)")] string value, [Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID, value, portalID);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_SettingUpdate")]
        public int sp_SettingUpdate([Parameter(Name="SettingID", DbType="Int")] System.Nullable<int> settingID, [Parameter(Name="Name", DbType="NVarChar(200)")] string name, [Parameter(Name="Value", DbType="NVarChar(2000)")] string value, [Parameter(Name="Description", DbType="NText")] string description)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), settingID, name, value, description);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_GetPortalSEONameByPortalID")]
        public ISingleResult<sp_GetPortalSEONameByPortalIDResult> sp_GetPortalSEONameByPortalID([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID);
            return ((ISingleResult<sp_GetPortalSEONameByPortalIDResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_PortalAdd")]
        public int sp_PortalAdd([Parameter(Name="PortalName", DbType="NVarChar(200)")] string portalName, [Parameter(Name="IsParent", DbType="Bit")] System.Nullable<bool> isParent, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalName, isParent, username);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_PortalDelete")]
        public int sp_PortalDelete([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, username);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_PortalUpdate")]
        public int sp_PortalUpdate([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="PortalName", DbType="NVarChar(200)")] string portalName, [Parameter(Name="IsParent", DbType="Bit")] System.Nullable<bool> isParent, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, portalName, isParent, username);
            return ((int)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_PortalGetByPortalID")]
        public ISingleResult<sp_PortalGetByPortalIDResult> sp_PortalGetByPortalID([Parameter(Name="PortalID", DbType="Int")] System.Nullable<int> portalID, [Parameter(Name="Username", DbType="NVarChar(256)")] string username)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), portalID, username);
            return ((ISingleResult<sp_PortalGetByPortalIDResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.sp_PortalGetList")]
        public ISingleResult<sp_PortalGetListResult> sp_PortalGetList()
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
            return ((ISingleResult<sp_PortalGetListResult>)(result.ReturnValue));
        }
		
        [Function(Name="dbo.usp_Aspx_AddStoreSubscriber")]
        public int usp_Aspx_AddStoreSubscriber([Parameter(Name="StoreName", DbType="NVarChar(256)")] string storeName, [Parameter(Name="FirstName", DbType="NVarChar(256)")] string firstName, [Parameter(Name="LastName", DbType="NVarChar(256)")] string lastName, [Parameter(Name="Email", DbType="NVarChar(100)")] string email, [Parameter(Name="CompanyName", DbType="NVarChar(256)")] string companyName, [Parameter(Name="Contact", DbType="Bit")] System.Nullable<bool> contact, [Parameter(Name="IsParent", DbType="Bit")] System.Nullable<bool> isParent, [Parameter(Name="Username", DbType="NVarChar(256)")] string username, [Parameter(Name="Password", DbType="NVarChar(128)")] string password, [Parameter(Name="PasswordSalt", DbType="NVarChar(128)")] string passwordSalt, [Parameter(Name="PasswordFormat", DbType="Int")] System.Nullable<int> passwordFormat, [Parameter(Name="IsFromFront", DbType="Bit")] System.Nullable<bool> isFromFront, [Parameter(Name="CustomerID", DbType="Int")] ref System.Nullable<int> customerID)
        {
            IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), storeName, firstName, lastName, email, companyName, contact, isParent, username, password, passwordSalt, passwordFormat, isFromFront, customerID);
            customerID = ((System.Nullable<int>)(result.GetParameterValue(12)));
            return ((int)(result.ReturnValue));
        }
    }

    public partial class sp_SettingBySettingIDResult
    {
		
        private int _SettingID;
		
        private string _Name;
		
        private string _Value;
		
        private string _Description;
		
        public sp_SettingBySettingIDResult()
        {
        }
		
        [Column(Storage="_SettingID", DbType="Int NOT NULL")]
        public int SettingID
        {
            get
            {
                return this._SettingID;
            }
            set
            {
                if ((this._SettingID != value))
                {
                    this._SettingID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_Value", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if ((this._Value != value))
                {
                    this._Value = value;
                }
            }
        }
		
        [Column(Storage="_Description", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }
    }

    public partial class sp_SettingListResult
    {
		
        private int _SettingID;
		
        private string _Name;
		
        private string _Value;
		
        private string _Description;
		
        public sp_SettingListResult()
        {
        }
		
        [Column(Storage="_SettingID", DbType="Int NOT NULL")]
        public int SettingID
        {
            get
            {
                return this._SettingID;
            }
            set
            {
                if ((this._SettingID != value))
                {
                    this._SettingID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_Value", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if ((this._Value != value))
                {
                    this._Value = value;
                }
            }
        }
		
        [Column(Storage="_Description", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                if ((this._Description != value))
                {
                    this._Description = value;
                }
            }
        }
    }

    public partial class sp_SettingPortalByPortalIDResult
    {
		
        private System.Nullable<int> _SettingPortalID;
		
        private System.Nullable<int> _SettingID;
		
        private string _Value;
		
        private System.Nullable<int> _PortalID;
		
        private string _Name;
		
        private string _DefaultValue;
		
        public sp_SettingPortalByPortalIDResult()
        {
        }
		
        [Column(Storage="_SettingPortalID", DbType="Int")]
        public System.Nullable<int> SettingPortalID
        {
            get
            {
                return this._SettingPortalID;
            }
            set
            {
                if ((this._SettingPortalID != value))
                {
                    this._SettingPortalID = value;
                }
            }
        }
		
        [Column(Storage="_SettingID", DbType="Int")]
        public System.Nullable<int> SettingID
        {
            get
            {
                return this._SettingID;
            }
            set
            {
                if ((this._SettingID != value))
                {
                    this._SettingID = value;
                }
            }
        }
		
        [Column(Storage="_Value", DbType="NVarChar(2000)")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if ((this._Value != value))
                {
                    this._Value = value;
                }
            }
        }
		
        [Column(Storage="_PortalID", DbType="Int")]
        public System.Nullable<int> PortalID
        {
            get
            {
                return this._PortalID;
            }
            set
            {
                if ((this._PortalID != value))
                {
                    this._PortalID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_DefaultValue", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
        public string DefaultValue
        {
            get
            {
                return this._DefaultValue;
            }
            set
            {
                if ((this._DefaultValue != value))
                {
                    this._DefaultValue = value;
                }
            }
        }
    }

    public partial class sp_SettingPortalBySettingIDResult
    {
		
        private int _SettingPortalID;
		
        private int _SettingID;
		
        private string _Value;
		
        private int _PortalID;
		
        private string _Name;
		
        private string _DefaultValue;
		
        public sp_SettingPortalBySettingIDResult()
        {
        }
		
        [Column(Storage="_SettingPortalID", DbType="Int NOT NULL")]
        public int SettingPortalID
        {
            get
            {
                return this._SettingPortalID;
            }
            set
            {
                if ((this._SettingPortalID != value))
                {
                    this._SettingPortalID = value;
                }
            }
        }
		
        [Column(Storage="_SettingID", DbType="Int NOT NULL")]
        public int SettingID
        {
            get
            {
                return this._SettingID;
            }
            set
            {
                if ((this._SettingID != value))
                {
                    this._SettingID = value;
                }
            }
        }
		
        [Column(Storage="_Value", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if ((this._Value != value))
                {
                    this._Value = value;
                }
            }
        }
		
        [Column(Storage="_PortalID", DbType="Int NOT NULL")]
        public int PortalID
        {
            get
            {
                return this._PortalID;
            }
            set
            {
                if ((this._PortalID != value))
                {
                    this._PortalID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200)")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_DefaultValue", DbType="NVarChar(2000)")]
        public string DefaultValue
        {
            get
            {
                return this._DefaultValue;
            }
            set
            {
                if ((this._DefaultValue != value))
                {
                    this._DefaultValue = value;
                }
            }
        }
    }

    public partial class sp_SettingPortalListResult
    {
		
        private int _SettingPortalID;
		
        private int _SettingID;
		
        private string _Value;
		
        private int _PortalID;
		
        public sp_SettingPortalListResult()
        {
        }
		
        [Column(Storage="_SettingPortalID", DbType="Int NOT NULL")]
        public int SettingPortalID
        {
            get
            {
                return this._SettingPortalID;
            }
            set
            {
                if ((this._SettingPortalID != value))
                {
                    this._SettingPortalID = value;
                }
            }
        }
		
        [Column(Storage="_SettingID", DbType="Int NOT NULL")]
        public int SettingID
        {
            get
            {
                return this._SettingID;
            }
            set
            {
                if ((this._SettingID != value))
                {
                    this._SettingID = value;
                }
            }
        }
		
        [Column(Storage="_Value", DbType="NVarChar(2000) NOT NULL", CanBeNull=false)]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                if ((this._Value != value))
                {
                    this._Value = value;
                }
            }
        }
		
        [Column(Storage="_PortalID", DbType="Int NOT NULL")]
        public int PortalID
        {
            get
            {
                return this._PortalID;
            }
            set
            {
                if ((this._PortalID != value))
                {
                    this._PortalID = value;
                }
            }
        }
    }

    public partial class sp_GetPortalSEONameByPortalIDResult
    {
		
        private int _PortalID;
		
        private string _Name;
		
        private string _SEOName;
		
        private System.Nullable<bool> _IsParent;
		
        public sp_GetPortalSEONameByPortalIDResult()
        {
        }
		
        [Column(Storage="_PortalID", DbType="Int NOT NULL")]
        public int PortalID
        {
            get
            {
                return this._PortalID;
            }
            set
            {
                if ((this._PortalID != value))
                {
                    this._PortalID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_SEOName", DbType="NChar(100)")]
        public string SEOName
        {
            get
            {
                return this._SEOName;
            }
            set
            {
                if ((this._SEOName != value))
                {
                    this._SEOName = value;
                }
            }
        }
		
        [Column(Storage="_IsParent", DbType="Bit")]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this._IsParent;
            }
            set
            {
                if ((this._IsParent != value))
                {
                    this._IsParent = value;
                }
            }
        }
    }

    public partial class sp_PortalGetByPortalIDResult
    {
		
        private int _PortalID;
		
        private string _Name;
		
        private string _SEOName;
		
        private System.Nullable<bool> _IsParent;
		
        public sp_PortalGetByPortalIDResult()
        {
        }
		
        [Column(Storage="_PortalID", DbType="Int NOT NULL")]
        public int PortalID
        {
            get
            {
                return this._PortalID;
            }
            set
            {
                if ((this._PortalID != value))
                {
                    this._PortalID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_SEOName", DbType="NChar(100)")]
        public string SEOName
        {
            get
            {
                return this._SEOName;
            }
            set
            {
                if ((this._SEOName != value))
                {
                    this._SEOName = value;
                }
            }
        }
		
        [Column(Storage="_IsParent", DbType="Bit")]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this._IsParent;
            }
            set
            {
                if ((this._IsParent != value))
                {
                    this._IsParent = value;
                }
            }
        }
    }

    public partial class sp_PortalGetListResult
    {
		
        private int _PortalID;
		
        private string _Name;
		
        private string _SEOName;
		
        private System.Nullable<bool> _IsParent;
		
        private string _DefaultPage;
		
        public sp_PortalGetListResult()
        {
        }
		
        [Column(Storage="_PortalID", DbType="Int NOT NULL")]
        public int PortalID
        {
            get
            {
                return this._PortalID;
            }
            set
            {
                if ((this._PortalID != value))
                {
                    this._PortalID = value;
                }
            }
        }
		
        [Column(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                if ((this._Name != value))
                {
                    this._Name = value;
                }
            }
        }
		
        [Column(Storage="_SEOName", DbType="NVarChar(100)")]
        public string SEOName
        {
            get
            {
                return this._SEOName;
            }
            set
            {
                if ((this._SEOName != value))
                {
                    this._SEOName = value;
                }
            }
        }
		
        [Column(Storage="_IsParent", DbType="Bit")]
        public System.Nullable<bool> IsParent
        {
            get
            {
                return this._IsParent;
            }
            set
            {
                if ((this._IsParent != value))
                {
                    this._IsParent = value;
                }
            }
        }
		
        [Column(Storage="_DefaultPage", DbType="NVarChar(256)")]
        public string DefaultPage
        {
            get
            {
                return this._DefaultPage;
            }
            set
            {
                if ((this._DefaultPage != value))
                {
                    this._DefaultPage = value;
                }
            }
        }
    }
}

#pragma warning restore 1591
